name: Update Lambda Layer

on:
  push:
    paths:
      - 'requirements.txt'

jobs:
  update-layer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        mkdir python
        pip install -r requirements.txt -t python
        zip -r layer.zip python

    - name: Deploy Layer
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: |
        aws lambda publish-layer-version \
          --layer-name PresignedURLLayer \
          --zip-file fileb://layer.zip

    - name: Clean up
      run: |
        rm -rf python layer.zip
